### ISSUE TITLE
Server Error when navigation storefront: Workflow with id "create-product-variants" and step definition already exists.

### ISSUE THREAD

**Issue by Garabed96** [loadpipe/Hamza-medusa#11]
### Useful links: 
Seems like adrien2p fixed some orchestration bug in latest version of medusa: https://github.com/medusajs/medusa/releases

### BUG: 
```
Server Error
Error: Workflow with id "create-product-variants" and step definition already exists.
```

### Steps to reproduce: 

These steps to reproduce are for main branch. I have reverted some of the work done with products on client side in this branch [branch](https://github.com/loadpipe/Hamza-medusa/tree/main-product-variant-issue)

**hamza-client:**
1. Remove the node_modules folder
2. Remove .next
3. Remove yarn.lock

**hamza-server:**
1. Remove the .cache folder
2. Remove the dist folder
3. Remove the node_modules folder
4. Remove the build folder
5. Remove yarn.lock

**Docker:**
1. docker-compose down
2. docker volume rm <db_volume>
3. docker images rm <images...>
4. docker-compose up -d
5. yarn install (client && server)
6. yarn build
7. medusa migrations run
8. medusa seed --seed-file=data/seed.json
9. yarn dev

### On Initial Load: **hamza-server console** 
```
error:   Cart with cart_01HT4RV1GXKN9VPDAFSRMBC6EY was not found
Error: Cart with cart_01HT4RV1GXKN9VPDAFSRMBC6EY was not found
    at CartService.<anonymous> (/Users/garonazarian/Documents/Hamza-medusa/hamza-server/node_modules/@medusajs/medusa/dist/services/cart.js:228:35)
    at step (/Users/garonazarian/Documents/Hamza-medusa/hamza-server/node_modules/@medusajs/medusa/dist/services/cart.js:59:23)
    at Object.next (/Users/garonazarian/Documents/Hamza-medusa/hamza-server/node_modules/@medusajs/medusa/dist/services/cart.js:40:53)
    at fulfilled (/Users/garonazarian/Documents/Hamza-medusa/hamza-server/node_modules/@medusajs/medusa/dist/services/cart.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'not_found',
  code: undefined,
  date: 2024-03-29T13:17:02.471Z
}
::1 - - [29/Mar/2024:13:17:02 +0000] "GET /store/carts/cart_01HT4RV1GXKN9VPDAFSRMBC6EY HTTP/1.1" 404 88 "-" "axios/0.24.0"
::1 - - [29/Mar/2024:13:17:02 +0000] "GET /store/product-categories?limit=100&offset=0 HTTP/1.1" 200 1913 "-" "axios/0.24.0"
::1 - - [29/Mar/2024:13:17:12 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:17:12 +0000] "GET /store/customers/me HTTP/1.1" 401 - "-" "axios/0.24.0"
```
### On Initial Load: **hamza-client console**
This one is very long but its just a simple GET error for the same cart item / id (I'm abbreviating it for convenience sake)
```
 _header: 'GET /store/carts/cart_01HT4RV1GXKN9VPDAFSRMBC6EY HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'next: [object Object]\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: localhost:9000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/store/carts/cart_01HT4RV1GXKN9VPDAFSRMBC6EY',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',

    },
    data: {
      type: 'not_found',
      message: 'Cart with cart_01HT4RV1GXKN9VPDAFSRMBC6EY was not found'
    }
```

### ON NAVIGATION: 
This occurs in all of these instances but in some instances it doesn't happen on initial load.
This can be any action such as clicking (Cart / Shop / Product (on home page) )

### hamza-server console: 

```
::1 - - [29/Mar/2024:13:25:16 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:25:17 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:25:28 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:25:35 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:25:35 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
::1 - - [29/Mar/2024:13:25:36 +0000] "GET /store/regions HTTP/1.1" 200 2315 "-" "Next.js Middleware"
```

### hamza-client console:
 ```
⨯ node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js (36:0) @ WorkflowManager.register
 ⨯ Error: Workflow with id "create-product-variants" and step definition already exists.
    at WorkflowManager.register (webpack-internal:///(rsc)/./node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js:36:23)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/core-flows/dist/definition/product/create-product-variants.js:89:33)
    at (rsc)/./node_modules/@medusajs/core-flows/dist/definition/product/create-product-variants.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:3725:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/core-flows/dist/definition/product/index.js:30:46)
    at (rsc)/./node_modules/@medusajs/core-flows/dist/definition/product/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:3769:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/core-flows/dist/definition/index.js:21:14)
    at (rsc)/./node_modules/@medusajs/core-flows/dist/definition/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:3329:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/core-flows/dist/index.js:35:14)
    at (rsc)/./node_modules/@medusajs/core-flows/dist/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:5001:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/inventory-items/create-inventory-item.js:93:20)
    at (rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/inventory-items/create-inventory-item.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:16514:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/inventory-items/index.js:34:31)
    at (rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/inventory-items/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:16624:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/index.js:44:41)
    at (rsc)/./node_modules/@medusajs/medusa/dist/api/routes/admin/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:16492:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/medusa/dist/api/index.js:35:31)
    at (rsc)/./node_modules/@medusajs/medusa/dist/api/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:14292:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@medusajs/medusa/dist/index.js:17:14)
    at (rsc)/./node_modules/@medusajs/medusa/dist/index.js (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/vendor-chunks/@medusajs.js:23642:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:46:74)
    at (rsc)/./src/lib/data/index.ts (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:2944:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:8:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:3422:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:2756:1)
    at Function.__webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at async eB (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:401104)
    at async ru (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6371)
    at async /Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:9079
    at async Promise.all (index 0)
    at async ru (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:8785)
    at async /Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:9079
    at async Promise.all (index 0)
    at async ru (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:8785)
    at async rc (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:11042)
    at async rv (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:13244)
    at async doRender (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/server/base-server.js:1378:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/server/base-server.js:1527:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/node_modules/next/dist/server/base-server.js:1447:28) {
  page: '/usstore'
}
null
 ⨯ node_modules/@medusajs/orchestration/dist/workflow/workflow-manager.js (36:0) @ WorkflowManager.register
 ⨯ Error: Workflow with id "create-product-variants" and step definition already exists.
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (./src/lib/data/index.ts:46:74)
    at (rsc)/./src/lib/data/index.ts (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:2944:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (./src/modules/layout/templates/footer/index.tsx:8:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:3422:1)
    at __webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at eval (layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/app/[countryCode]/(main)/page.js:2756:1)
    at Function.__webpack_require__ (/Users/garonazarian/Documents/Hamza-medusa/hamza-client/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
digest: "4033974856"
null```

**Comment by jrkosinski** [comment]
6. medusa migrations run
7. yarn build
8. medusa migrations run
... medusa migrations run is steps 6 & 8 - is that on purpose? I feel like step 6 must be a mistake.

**Comment by Garabed96** [comment]
> 6. medusa migrations run
> 7. yarn build
> 8. medusa migrations run
>    ... medusa migrations run is steps 6 & 8 - is that on purpose? I feel like step 6 must be a mistake.

I'm just running the default migrations before building and running the custom migrations we've added

**Comment by Garabed96** [comment]
Ok fixed it, it is an unnecessary step / mistake.

**Comment by Garabed96** [comment]
This seems related: https://github.com/medusajs/medusa/issues/4998

I'll be going through yarn.locks && making sure modules are compatible, etc.

**Comment by Garabed96** [comment]
This is leading back to the original error we were getting a couple weeks ago:
`Import trace for requested module:
./node_modules/@medusajs/medusa/dist/interfaces/index.js
./node_modules/@medusajs/medusa/dist/index.js
./src/modules/account/actions.ts
./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22%2FUsers%2Fgaronazarian%2FDocuments%2FHamza-medusa%2Fhamza-client%2Fsrc%2Fmodules%2Faccount%2Factions.ts%22%2C%5B%22updateCustomerEmail%22%2C%22addCustomerShippingAddress%22%2C%22updateCustomerShippingAddress%22%2C%22deleteCustomerShippingAddress%22%2C%22updateCustomerPhone%22%2C%22updateCustomerName%22%2C%22updateCustomerPassword%22%2C%22signOut%22%2C%22signUp%22%2C%22updateCustomerBillingAddress%22%2C%22logCustomerIn%22%5D%5D%5D&__client_imported__=true!
 ⨯ ./node_modules/@medusajs/medusa/dist/interfaces/models/base-entity.js:13:0
Module not found: Can't resolve 'typeorm'
`

**Comment by MoscatelliMarco** [comment]
I am having your same error on my machine:
Error: Workflow with id "create-product-variants" and step definition already exists.

Do you mind if I ask you how did you fix it? Because even though this issue is closed my problem is persisting

**Comment by Garabed96** [comment]
@MoscatelliMarco Hi for us the issue was a frontend bug in one of the modules where we had extended a medusa core class. We also had typeorm installed in the client end, once we removed typeorm, we saw the path trace for the actual bug.

**Comment by MoscatelliMarco** [comment]
I am not using any storefront, for now I am just creating a plugin with an entity for a store admin UI, and the code is not working.
